<template>
    <q-card class="file-form-card">
      <q-card-section>
        <div class="text-h6 text-center">Información del Archivo</div>
      </q-card-section>
  
      <q-card-section class="q-gutter-md">
        <q-input
          filled
          v-model="identificationNumber"
          label="Número de Documento de Identificación"
          :rules="[val => !!val || 'Este campo es obligatorio']"
          lazy-rules
          clearable
        />
        <q-input
          filled
          v-model="firstName"
          label="Nombre"
          :rules="[val => !!val || 'Este campo es obligatorio']"
          lazy-rules
          clearable
        />
        <q-input
          filled
          v-model="lastName"
          label="Apellido"
          :rules="[val => !!val || 'Este campo es obligatorio']"
          lazy-rules
          clearable
        />
        <q-input
          filled
          v-model="fileName"
          label="Nombre del Archivo"
          :rules="[val => !!val || 'Este campo es obligatorio']"
          lazy-rules
          clearable
        />
        <q-input
          filled
          v-model.number="pagesAmount"
          label="Cantidad de Páginas"
          type="number"
          :rules="[val => !!val || 'Este campo es obligatorio']"
          lazy-rules
          clearable
        />
        <q-input
          filled
          v-model="autoGeneratedNumber"
          label="Número Generado Automáticamente"
          :rules="[val => !!val || 'Este campo es obligatorio']"
          lazy-rules
          clearable
          readonly
        />
        <q-file
          v-model="file"
          label="Seleccionar Archivo"
          filled
          :rules="[val => !!val || 'Debes seleccionar un archivo']"
          lazy-rules
        />
        <q-btn @click="onSubmit" label="Enviar" color="primary" class="full-width custom-button" />
        <div v-if="errorMessage" class="text-negative">{{ errorMessage }}</div>
      </q-card-section>
    </q-card>
  </template>
  
  <script setup lang="ts">
  import { ref } from 'vue';
  import { useRouter } from 'vue-router';
  
  defineOptions({
    name: 'FileFormPage'
  });
  
  const router = useRouter();
  const identificationNumber = ref('');
  const firstName = ref('');
  const lastName = ref('');
  const fileName = ref('');
  const pagesAmount = ref<number | null>(null);
  const autoGeneratedNumber = ref(Math.random().toString().slice(2, 12)); // Generar un número aleatorio
  const file = ref<File | null>(null);
  const errorMessage = ref<string | null>(null);
  
  function onSubmit() {
    errorMessage.value = null;
  
    if (identificationNumber.value && firstName.value && lastName.value && fileName.value && pagesAmount.value && file.value) {
      console.log('Archivo enviado:', {
        identificationNumber: identificationNumber.value,
        firstName: firstName.value,
        lastName: lastName.value,
        fileName: fileName.value,
        pagesAmount: pagesAmount.value,
        autoGeneratedNumber: autoGeneratedNumber.value,
        file: file.value.name,
      });
      
      // Aquí podrías añadir lógica para enviar los datos a tu backend o almacenar en el estado
      router.push('/home'); // Redirigir a la página del dashboard después del envío
    } else {
      errorMessage.value = 'Por favor, completa todos los campos';
    }
  }
  </script>
  
  <style scoped>
  .file-form-card {
    max-width: 500px; /* Ancho máximo del card */
    margin: 20px auto; /* Centra el card horizontalmente y añade margen vertical */
    padding: 20px; /* Añade padding interno al card */
    border-radius: 10px; /* Esquinas redondeadas para el card */
    box-shadow: 0 2px 10px rgba(0, 0, 0, 0.1); /* Sombra sutil */
    background-color: #f9f9f9; /* Fondo suave */
  }
  
  .custom-button {
    border-radius: 15px; /* Esquinas redondeadas para el botón */
  }
  
  .q-btn {
    transition: background-color 0.3s; /* Efecto de transición para el color de fondo */
  }
  
  .q-btn:hover {
    opacity: 0.9; /* Ligera reducción de opacidad en hover */
  }
  
  .text-center {
    text-align: center; /* Centra el texto */
  }
  </style>
  