<template>
  <q-card class="file-detail-card">
    <q-card-section>
      <div class="text-h6 title">Detalles del Archivo</div>
      <q-separator />

      <q-form class="file-detail-form">
        <q-input v-model="file.id" label="Número de Identificación del Documento" readonly />
        <q-input v-model="file.firstName" label="Nombre" readonly />
        <q-input v-model="file.lastName" label="Apellido" readonly />
        <q-input v-model="file.fileName" label="Nombre del Archivo" readonly />
        <q-input v-model="file.pageCount" label="Cantidad de Páginas" readonly />
        <q-input v-model="file.autoGeneratedId" label="ID Autogenerado" readonly />

        <q-card class="preview-card">
          <q-card-section>
            <div v-if="file.preview" class="text-h6">Vista Previa del Archivo</div>
            <img v-if="file.preview" :src="file.preview" alt="Vista Previa" class="preview-image" />
          </q-card-section>
        </q-card>
      </q-form>

      <q-btn @click="goBack" label="Regresar" color="secondary" class="q-mt-md go-back-button" />
    </q-card-section>
  </q-card>
</template>

<script setup lang="ts">
import { ref, onMounted } from 'vue';
import { useRouter } from 'vue-router';

defineOptions({
  name: 'FileDetailPage'
});

const router = useRouter();

const files = ref([
  {
    id: '1',
    firstName: 'Juan',
    lastName: 'Pérez',
    fileName: 'Ejemplo de Documento.pdf',
    pageCount: 10,
    autoGeneratedId: '0000000001',
    preview: 'https://placehold.co/600x400',
  },
  {
    id: '2',
    firstName: 'Ana',
    lastName: 'Gómez',
    fileName: 'Informe de Ventas.xlsx',
    pageCount: 5,
    autoGeneratedId: '0000000002',
    preview: 'https://placehold.co/600x400',
  },
  {
    id: '3',
    firstName: 'Luis',
    lastName: 'Martínez',
    fileName: 'Presentación.pptx',
    pageCount: 12,
    autoGeneratedId: '0000000003',
    preview: 'https://placehold.co/600x400',
  },
  {
    id: '4',
    firstName: 'María',
    lastName: 'López',
    fileName: 'Propuesta de Proyecto.docx',
    pageCount: 8,
    autoGeneratedId: '0000000004',
    preview: 'https://placehold.co/600x400',
  },
  {
    id: '5',
    firstName: 'Carlos',
    lastName: 'Hernández',
    fileName: 'Plan de Marketing.pdf',
    pageCount: 20,
    autoGeneratedId: '0000000005',
    preview: 'https://placehold.co/600x400',
  },
  {
    id: '6',
    firstName: 'Laura',
    lastName: 'García',
    fileName: 'Estudio de Mercado.pptx',
    pageCount: 15,
    autoGeneratedId: '0000000006',
    preview: 'https://placehold.co/600x400',
  },
]);

const file = ref({
  id: '',
  firstName: '',
  lastName: '',
  fileName: '',
  pageCount: 0,
  autoGeneratedId: '',
  preview: '',
});

function getFileById(id: string) {
  const foundFile = files.value.find(file => file.id === id);
  if (foundFile) {
    file.value = foundFile;
  } else {
    console.error('Archivo no encontrado');
  }
}

onMounted(() => {
  const fileId = router.currentRoute.value.params.id as string;
  getFileById(fileId);
});

function goBack() {
  router.go(-1);
}
</script>

<style scoped>
.file-detail-card {
  background-color: #f8f9fa;
  box-shadow: 0 4px 20px rgba(0, 0, 0, 0.1);
  border-radius: 8px;
  padding: 20px;
}

.title {
  color: #343a40;
  font-weight: bold;
}

.file-detail-form {
  margin-top: 10px;
}

.preview-card {
  margin-top: 20px;
  background-color: #ffffff;
  border: 1px solid #dee2e6;
  border-radius: 8px;
  padding: 10px;
}

.preview-image {
  max-width: 100%;
  height: auto;
  border-radius: 8px;
  box-shadow: 0 2px 10px rgba(0, 0, 0, 0.1);
}

.go-back-button {
  width: 100%;
  font-weight: bold;
}
</style>
