<template>
  <q-card>
    <q-card-section>
      <div class="text-h6">Archivos</div>
      <q-separator />
      <div class="grid-container">
        <div v-for="file in files" :key="file.id" class="grid-item">
          <q-card class="file-card">
            <q-card-section class="card-content">
              <q-icon
                v-if="file.isFolder"
                name="folder"
                size="40px" 
                class="file-icon"
              />
              <q-img
                v-else
                :src="file.preview"
                alt="Vista previa"
                class="file-preview"
                :style="{ maxHeight: '100px', maxWidth: '100%' }" 
              />
              <div class="file-info">
                <div class="file-name">{{ file.fileName }}</div>
                <div class="file-owner">{{ file.firstName }} {{ file.lastName }}</div>
                <div>Páginas: {{ file.pageCount }}</div>
              </div>
            </q-card-section>
            <q-card-actions class="card-actions">
              <q-btn
                @click="pinFile(file)"
                icon="push_pin"
                :color="file.isPinned ? 'yellow' : 'primary'"
                class="action-btn"
              />
              <div class="action-buttons">
                <q-btn @click="viewFileInfo(file)" icon="visibility" color="primary" />
                <q-btn @click="editFile(file)" icon="edit" color="secondary" />
                <q-btn 
                  @click="deleteFile(file)" 
                  icon="delete" 
                  color="negative" 
                  :disabled="file.isPinned" 
                />
                <q-btn 
                  @click="sendFile(file)" 
                  icon="send" 
                  color="accent" 
                  @click.prevent="file.isFolder ? openFolder(file) : sendFile(file)" 
                />
              </div>
            </q-card-actions>
          </q-card>
        </div>
      </div>
    </q-card-section>
  </q-card>
</template>

<script setup lang="ts">
import { ref } from 'vue';
import { useRouter } from 'vue-router';

interface File {
  id: string;
  firstName: string;
  lastName: string;
  fileName: string;
  pageCount: number;
  autoGeneratedId: string;
  preview: string;
  isPinned: boolean;
  isFolder: boolean;
}

const router = useRouter();

const files = ref<File[]>([
  {
    id: '1',
    firstName: 'Juan',
    lastName: 'Pérez',
    fileName: 'Ejemplo de Documento.pdf',
    pageCount: 10,
    autoGeneratedId: '0000000001',
    preview: 'https://placehold.co/600x400',
    isPinned: false,
    isFolder: false,
  },
  {
    id: '2',
    firstName: 'Ana',
    lastName: 'Gómez',
    fileName: 'Informes',
    pageCount: 0,
    autoGeneratedId: '0000000002',
    preview: '',
    isPinned: false,
    isFolder: true,
  },
  {
    id: '3',
    firstName: 'Luis',
    lastName: 'Martínez',
    fileName: 'Presentación.pptx',
    pageCount: 12,
    autoGeneratedId: '0000000003',
    preview: 'https://placehold.co/600x400',
    isPinned: false,
    isFolder: false,
  },
  {
    id: '4',
    firstName: 'María',
    lastName: 'López',
    fileName: 'Proyecto de Trabajo',
    pageCount: 5,
    autoGeneratedId: '0000000004',
    preview: '',
    isPinned: false,
    isFolder: true,
  },
  {
    id: '5',
    firstName: 'Pedro',
    lastName: 'Ramírez',
    fileName: 'Informe Anual.xlsx',
    pageCount: 20,
    autoGeneratedId: '0000000005',
    preview: 'https://placehold.co/600x400',
    isPinned: false,
    isFolder: false,
  },
  {
    id: '6',
    firstName: 'Laura',
    lastName: 'García',
    fileName: 'Resumen de Reunión.docx',
    pageCount: 3,
    autoGeneratedId: '0000000006',
    preview: 'https://placehold.co/600x400',
    isPinned: false,
    isFolder: false,
  },
]);

function pinFile(file: File) {
  file.isPinned = !file.isPinned;
  console.log(file.isPinned ? 'Archivo anclado:' : 'Archivo desanclado:', file.fileName);
}

function viewFileInfo(file: File) {
  router.push(`/file/${file.id}`);
  console.log('Información del archivo:', file);
}

function editFile(file: File) {
  router.push({ name: 'file-form', query: { id: file.id } });
}

function deleteFile(file: File) {
  if (!file.isPinned) {
    const index = files.value.findIndex(f => f.id === file.id);
    if (index !== -1) {
      files.value.splice(index, 1);
      console.log('Archivo eliminado:', file.fileName);
    }
  } else {
    console.log('No se puede eliminar el archivo anclado:', file);
  }
}

function sendFile(file: File) {
  console.log('Enviando archivo:', file);
}

function openFolder(folder: File) {
  console.log('Abriendo carpeta:', folder.fileName);
}
</script>

<style scoped>
.grid-container {
  display: grid;
  grid-template-columns: repeat(auto-fill, minmax(200px, 1fr));
  gap: 16px;
}

.grid-item {
  display: flex;
  flex-direction: column;
}

.file-card {
  min-height: 300px;
  display: flex;
  flex-direction: column;
  justify-content: space-between;
}

.card-content {
  text-align: center;
  flex-grow: 1;
}

.file-icon {
  color: #ffb300;
}

.file-preview {
  width: 100%;
  height: auto;
  object-fit: cover;
}

.file-info {
  margin: 10px 0;
}

.file-name {
  font-weight: bold;
}

.file-owner {
  color: #666;
}

.card-actions {
  display: flex;
  justify-content: space-between;
  align-items: center;
}

.action-buttons {
  display: flex;
  gap: 8px;
}

.action-btn {
  margin-bottom: 8px;
}
</style>
