<template>
    <q-form @submit.prevent="submitForm">
      <q-input v-model="form.identificationNumber" label="Identification Document Number" required />
      <q-input v-model="form.firstName" label="First Name" required />
      <q-input v-model="form.lastName" label="Last Name" required />
      <q-input v-model="form.fileName" label="Name of the File" required />
      <q-input v-model="form.pages" label="Amount of Pages" type="number" required />
      <q-input v-model="autoGeneratedNumber" label="Auto Generated Number" readonly />
      <q-file v-model="form.fileInput" label="File Input" />
      <q-btn label="Submit" type="submit" color="primary" />
    </q-form>
  </template>
  
  <script lang="ts">
  import { defineComponent, ref } from 'vue';
  import { useFilesStore } from '../store/files';
  
  export default defineComponent({
    setup() {
      const filesStore = useFilesStore();
      const form = ref({
        identificationNumber: '',
        firstName: '',
        lastName: '',
        fileName: '',
        pages: 0,
        fileInput: null as File | null,
      });
      const autoGeneratedNumber = ref(Math.random().toString(36).substr(2, 10));
  
      const submitForm = () => {
        filesStore.addFile({
          ...form.value,
          id: autoGeneratedNumber.value,
          autoGeneratedNumber: autoGeneratedNumber.value,
          pinned: false,
        });
        form.value = { identificationNumber: '', firstName: '', lastName: '', fileName: '', pages: 0, fileInput: null };
        autoGeneratedNumber.value = Math.random().toString(36).substr(2, 10);
      };
  
      return { form, autoGeneratedNumber, submitForm };
    },
  });
  </script>
  